version: '1.0.1'

services:
  # classification:
  #   build:
  #     context: ./detection
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  
  segmentation:
    build:
      context: ./segmentation
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./segmentation/.env

  volume_estimation:
    build:
      context: ./volume_estimation
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./volume_estimation/.env