# -*- coding: utf-8 -*-
"""sam2_falai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANIZDgyaiyr_GYZ_8qqNCozCbEoNPfkE
"""


import os
import base64
import fal_client
from PIL import Image, ImageDraw
import matplotlib.pyplot as plt
import requests
from io import BytesIO

from google.colab import userdata
# userdata.get('FAL_KEY')

import os
os.environ['FAL_KEY'] = userdata.get('FAL_KEY')
print(os.getenv('FAL_KEY'))

fal_client.key = userdata.get('FAL_KEY')

# Read the local image and encode it as base64
image_path = "/content/20151127_114556.jpg"
if not os.path.exists(image_path):
    raise FileNotFoundError(f"Image file '{image_path}' not found in the current directory.")

image = Image.open(image_path)
image_width, image_height = image.size
print(f"Image width: {image_width}, Image height: {image_height}")

image_path = "/content/20151127_114556.jpg"
if not os.path.exists(image_path):
    raise FileNotFoundError(f"Image file '{image_path}' not found in the current directory.")

# Open the image and rotate it 0 degrees counterclockwise
with Image.open(image_path) as img:
    rotated_img = img.rotate(0, expand=True)

# Save the rotated image to a temporary in-memory buffer
from io import BytesIO
buffer = BytesIO()
rotated_img.save(buffer, format="JPEG")
buffer.seek(0)

# Encode the rotated image as base64
image_data = base64.b64encode(buffer.read()).decode("utf-8")
data_uri = f"data:image/jpeg;base64,{image_data}"
point_prompts = [
    {
      "y": 1600,
      "label": 1,
      "x": 2300
    },
  ]
box_prompts = [
    {
      "y_min": 1220,
      "x_max": 2680,
      "x_min": 2000,
      "y_max": 1950
    }]
# Define the segmentation arguments
arguments = {
    "image_url": data_uri,
    "output_format": "png",
    "prompts": point_prompts,
    "box_prompts": box_prompts
}

# Submit the request and track progress
def on_queue_update(update):
    if isinstance(update, fal_client.InProgress):
        for log in update.logs:
            print(log["message"])

result = fal_client.subscribe(
    "fal-ai/sam2/image",
    arguments=arguments,
    with_logs=True,
    on_queue_update=on_queue_update,
)

# Extract the segmented image URL
segmented_image_info = result.get("image", {})
segmented_image_url = segmented_image_info.get("url")

if not segmented_image_url:
    raise ValueError("Segmentation failed or no output URL returned.")


# Download the segmented image using requests
response = requests.get(segmented_image_url)
if response.status_code != 200:
    raise ValueError(f"Failed to download segmented image. HTTP Status Code: {response.status_code}")

segmented_image = Image.open(BytesIO(response.content))
segmented_image.save("segmented_im1.png")

# Display the original and segmented images
original_image = Image.open(image_path)
segmented_image = Image.open("segmented_im1.png")

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.title("Original Image")
plt.imshow(original_image)
plt.axis("off")

plt.subplot(1, 2, 2)
plt.title("Segmented Image")
plt.imshow(segmented_image)
plt.axis("off")

plt.show()

# Set the API key from the environment variable
api_key = os.getenv("FAL_KEY")
if not api_key:
    raise ValueError("FAL_KEY environment variable is not set. Please set it before running this notebook.")

fal_client.api_key = api_key

image_path = "/content/20151127_114556.jpg"
if not os.path.exists(image_path):
    raise FileNotFoundError(f"Image file '{image_path}' not found in the current directory.")

# Open the image and rotate it 90 degrees counterclockwise
with Image.open(image_path) as img:
    rotated_img = img.rotate(0, expand=True)

# Save the rotated image to a temporary in-memory buffer
from io import BytesIO
buffer = BytesIO()
rotated_img.save(buffer, format="JPEG")
buffer.seek(0)

# Encode the rotated image as base64
image_data = base64.b64encode(buffer.read()).decode("utf-8")
data_uri = f"data:image/jpeg;base64,{image_data}"

point_prompts = [
    {
      "y": 1000,
      "label": 1,
      "x": 1200
    },
  ]
box_prompts = [
    {
      "y_min": 667,
      "x_max": 1623,
      "x_min": 843,
      "y_max": 1467
    }]
# Define the segmentation arguments
arguments = {
    "image_url": data_uri,
    "output_format": "png",
    "prompts": point_prompts,
    "box_prompts": box_prompts
}

# Submit the request and track progress
def on_queue_update(update):
    if isinstance(update, fal_client.InProgress):
        for log in update.logs:
            print(log["message"])

result = fal_client.subscribe(
    "fal-ai/sam2/image",
    arguments=arguments,
    with_logs=True,
    on_queue_update=on_queue_update,
)

# Extract the segmented image URL
segmented_image_info = result.get("image", {})
segmented_image_url = segmented_image_info.get("url")

if not segmented_image_url:
    raise ValueError("Segmentation failed or no output URL returned.")


# Download the segmented image using requests
response = requests.get(segmented_image_url)
if response.status_code != 200:
    raise ValueError(f"Failed to download segmented image. HTTP Status Code: {response.status_code}")

segmented_image = Image.open(BytesIO(response.content))
segmented_image.save("segmented_im2.png")

# Display the original and segmented images
original_image = Image.open(image_path)
segmented_image = Image.open("segmented_im2.png")

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.title("Original Image")
plt.imshow(original_image)
plt.axis("off")

plt.subplot(1, 2, 2)
plt.title("Segmented Image")
plt.imshow(segmented_image)
plt.axis("off")

plt.show()

# Draw annotations
draw = ImageDraw.Draw(rotated_img)

# Draw points
for point in point_prompts:
    x, y = point["x"], point["y"]
    draw.ellipse([(x - 5, y - 5), (x + 5, y + 5)], fill="red", outline="red")

# Draw bounding boxes
for box in box_prompts:
    x_min, y_min = box["x_min"], box["y_min"]
    x_max, y_max = box["x_max"], box["y_max"]
    draw.rectangle([(x_min, y_min), (x_max, y_max)], outline="blue", width=3)

# Display the annotated rotated image
plt.figure(figsize=(10, 10))
plt.imshow(rotated_img)
plt.axis("off")
plt.title("Rotated Image with Annotations")
plt.show()

# Save the rotated and annotated image to base64
buffer = BytesIO()
rotated_img.save(buffer, format="JPEG")
buffer.seek(0)

# Annotate the original image with point and bounding box prompts
original_image = Image.open(image_path).convert("RGB")
annotated_image = original_image.copy()
draw = ImageDraw.Draw(annotated_image)

# Draw point prompts
for point in point_prompts:
    x, y, label = point["x"], point["y"], point["label"]
    color = "green" if label == 1 else "red"
    radius = 10
    draw.ellipse((x - radius, y - radius, x + radius, y + radius), fill=color, outline="black")
    draw.text((x + 15, y - 15), f"Label: {label}", fill=color)

# Draw bounding box prompts
for box in box_prompts:
    x_min, y_min, x_max, y_max = box["x_min"], box["y_min"], box["x_max"], box["y_max"]
    draw.rectangle([x_min, y_min, x_max, y_max], outline="blue", width=3)
    draw.text((x_min, y_min - 10), "Box", fill="blue")

# Display the annotated and segmented images
plt.figure(figsize=(15, 7))

plt.subplot(1, 3, 1)
plt.title("Original Image")
plt.imshow(original_image)
plt.axis("off")

plt.subplot(1, 3, 2)
plt.title("Annotated Image (Prompts)")
plt.imshow(annotated_image)
plt.axis("off")

plt.subplot(1, 3, 3)
plt.title("Segmented Image")
plt.imshow(segmented_image)
plt.axis("off")

plt.show()

# calculate pixel area
from PIL import Image
import numpy as np

# Load the segmented image
segmented_image_path = "segmented_im1.png"  # Replace with the path to your segmented image
segmented_image = Image.open(segmented_image_path).convert("L")  # Convert to grayscale

# Convert the image to a NumPy array
image_array = np.array(segmented_image)

# Define pixel intensity thresholds
white_threshold = 250  # Adjust for near-white
gray_min_threshold = 128
gray_max_threshold = 249

# Calculate the area of white pixels
white_pixel_count = np.sum(image_array >= white_threshold)

# Calculate the area of gray pixels
gray_pixel_count = np.sum((image_array >= gray_min_threshold) & (image_array <= gray_max_threshold))

# Display the results
pixel_area_white = white_pixel_count
pixel_area_gray = gray_pixel_count
total_pixels = image_array.size

print(f"Total Pixels: {total_pixels}")
print(f"White Pixel Area: {pixel_area_white}")
print(f"Gray Pixel Area: {pixel_area_gray}")

# calculate pixel area
from PIL import Image
import numpy as np

# Load the segmented image
segmented_image_path = "segmented_im2.png"  # Replace with the path to your segmented image
segmented_image = Image.open(segmented_image_path).convert("L")  # Convert to grayscale

# Convert the image to a NumPy array
image_array = np.array(segmented_image)

# Define pixel intensity thresholds
white_threshold = 250  # Adjust for near-white
gray_min_threshold = 128
gray_max_threshold = 249

# Calculate the area of white pixels
white_pixel_count = np.sum(image_array >= white_threshold)

# Calculate the area of gray pixels
gray_pixel_count = np.sum((image_array >= gray_min_threshold) & (image_array <= gray_max_threshold))

# Display the results
pixel_area_white = white_pixel_count
pixel_area_gray = gray_pixel_count
total_pixels = image_array.size

print(f"Total Pixels: {total_pixels}")
print(f"White Pixel Area: {pixel_area_white}")
print(f"Gray Pixel Area: {pixel_area_gray}")